### ISSUE TITLE
Strange SRAM entry point 

### ISSUE THREAD

**Issue by SundaresanN** [CTXz/stm32f1-picopwner#14]
Hi, i'm using stm32F103C8T6 blue pill. 

I'm getting the following error, 

    raise Exception("Could not determine SRAM entry point\nopenocd output: " + line)
Exception: Could not determine SRAM entry point
openocd output: xPSR: 0x01000000 pc: 0x08000150 msp: 00000000

I find it strange pc: 0x08000150. Its supposed to be 0x20000150. 

![Capture](https://github.com/CTXz/stm32f1-picopwner/assets/31757231/34bd9eb0-ba81-4baf-a56e-31b3b899331a)

Additional info, I'm running bare metal led blink example with RDP enabled. Is it necessary to run any specific application to make the exploit work?

Thanks!

**Comment by CTXz** [comment]
Based on the value of the `PC`, the device simply starts into flash instead of SRAM. This most likely implies that your boot pins are not being properly configured. I suspect `BOOT0` is the culprit in your case. Can you confirm it is correctly connected to the Pi's GPIO (GPIO5)? If you're confident, try pulling up the `BOOT0` pin via the jumper and see if the PC at least jumps into the SRAM. The exploit will obviously not work like this but it would confirm the Pi's not doing its duty of pulling the pin high.  If necessary, check out if the pin is being set by the pi using an oscilloscope.

**Comment by CTXz** [comment]
Since this issue has been inactive for a prolonged period of time now, I'll be closing it. I'll gladly reopen it if necessary

**Comment by Alex-com2** [comment]
Hello! When I try to read STM32F103RCT6 get an error the moment st-link v2 is connected. BOOT1 (Pin 28) pulled directly to the power supply, without a resistor, BOOT0 (Pin 60) also without a resistor. Voltage at BOOT0 +3,23 V. In CubeProgrammer, the connection occurs (photo of registers attached). All Pins are connected correctly. The device provides a remote firmware update. On the other STM32F103RCT6 purchased in the store, everything works.
![Screen_Terminal](https://github.com/CTXz/stm32f1-picopwner/assets/172990817/cccfdd4c-3aaa-4e6b-97d4-7a2af84fba17)
![ScreenCuberPro](https://github.com/CTXz/stm32f1-picopwner/assets/172990817/ad3ce41b-30b8-4360-93d3-ae787181116d)
