### ISSUE TITLE
STM32F4xx RDP 2

### ISSUE THREAD

**Issue by Mesteery** [CTXz/stm32f1-picopwner#23]
I came across this project which looks promising and I was wondering if it was able to remove the write protection RDP 2 so stm32 can be flashed. Thanks

**Comment by CTXz** [comment]
Hi, this exploit does not work on the STM32F4, let alone one with RDP2. If you wish to be updated about potential progress regarding the f4, the keep an eye on this thread: 

https://github.com/CTXz/stm32f1-picopwner/issues/13

**Comment by deividAlfa** [comment]
RDP is irreversible

**Comment by Angelic47** [comment]
Hi, the RDP2 can't be removed, even we hacked into the CPU and get arbitrary code execution - it's readonly, designed by ST for a security defense. 
In theory, the RDP2 can be temporary downgrade to RDP1, and for some combo glitches it could write the flash, implement a bootloader and makes it flashable again. 
But it's a quite challenging, due to the numerous security defenses filled by ST, makes it very hard to achieve. 
So downgrade the RDP 2 and reprogram the firmware will be worthless.

**Comment by mrx23dot** [comment]
But surely during boot the MCU reads the value of RDP option byte and compares it to RDP levels,
so if we would make it 1bit different with glitching it would become Level 1.
At least it would be good to unbrick/repurpose the chip.

Based on that logic the equal checks could be glitched, with EQ to NEQ
```
if RDP==level2
elif RDP==level1
elif RDP==level0
```

**Comment by deividAlfa** [comment]
Good luck with that, it's not impossible but requires extremely fast and small pulses (nano seconds), then finding the exact point where the stm32 reads the rdp.
If it takes 5000 instructions to start booting, you have to glitch each one, check if rdp is cleared, try again with +20ns, and so on, it's extremely time consuming.

There's no need to reinvent the wheel:
https://sec-consult.com/blog/detail/secglitcher-part-1-reproducible-voltage-glitching-on-stm32-microcontrollers/
